CREATE TABLE `t_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `open_id` varchar(64) DEFAULT NULL COMMENT '用户id',
  `UNION_ID` varchar(64) DEFAULT NULL,
  `real_name` varchar(64) DEFAULT NULL COMMENT '真实姓名',
  `user_name` varchar(128) NOT NULL COMMENT '登录账号',
  `password` varchar(64) NOT NULL,
  `phone` varchar(11) DEFAULT NULL COMMENT '手机号码',
  `email` varchar(64) DEFAULT NULL COMMENT '邮箱',
  `avatar_url` varchar(255) DEFAULT NULL COMMENT '用户头像地址',
  `gender` smallint(6) DEFAULT NULL COMMENT '用户的性别，值为1时是男性，值为2时是女性，值为0时是未知',
  `city` varchar(64) DEFAULT NULL COMMENT '用户所在城市',
  `province` varchar(64) DEFAULT NULL COMMENT '用户所在省份',
  `ip` varchar(15) DEFAULT NULL COMMENT 'ip地址',
  `country` varchar(64) DEFAULT NULL COMMENT '用户所在国家',
  `language` varchar(24) DEFAULT NULL COMMENT '用户的语言，简体中文为zh_CN',
  `type` smallint(6) DEFAULT NULL COMMENT '用户类型,1=微信用户，2=后台用户',
  `activation` smallint(6) DEFAULT '1' COMMENT '激活状态',
  `user_status` smallint(6) DEFAULT '1' COMMENT '状态：1=正常',
  `is_delete` smallint(6) NOT NULL DEFAULT '1' COMMENT '逻辑删除字段：-1=删除，1=未删除',
  `create_user` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=43175 DEFAULT CHARSET=utf8;

